language: node_js
sudo: false
branches:
  except:
    - /^greenkeeper.*/
node_js:
  - 8
  - 7
  - 6
  - 5
  - 4
  - 10
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - travis_retry npm test
after_success:
  - npm run codecov
